 name: Run Playwright tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install dependencies
      run: npm install

    - name: Run Playwright script
      env:
        MY_SECRET: ${{ secrets.TEST_SECRET }}
      run: node tests/access.js

         
    #"recommendhomepage": "tests/RecommendLinkHomePage.spec.js",
   # "recommendinnerview": "tests/RecommendLinkInnerView.spec.js",
   # "takeawayformatting": "tests/TakawayFormattingOption.spec.js",
   # "takeawayremoveprogress": "tests/TakawayFormattingOption.spec.js"

 