 name: Run Playwright tests

on:
  push:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm ci


    - name: Run Playwright script
      env:
        MY_SECRET: ${{ secrets.TEST_SECRET }}
      run: node tests/access.js

         
    #"recommendhomepage": "tests/RecommendLinkHomePage.spec.js",
   # "recommendinnerview": "tests/RecommendLinkInnerView.spec.js",
   # "takeawayformatting": "tests/TakawayFormattingOption.spec.js",
   # "takeawayremoveprogress": "tests/TakawayFormattingOption.spec.js"

 