# name: Playwright Tests
# on:
#   #push:
#     #branches: [ main, master ]
#   #pull_request:
#     #branches: [ main, master ]
# jobs:
#   test:
#     timeout-minutes: 60
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v3
#     - uses: actions/setup-node@v3
#       with:
#         node-version: 16
#     - name: Install dependencies
#       run: npm ci 
     
#     - name: Install Playwright Browsers
#       run: npx playwright install --with-deps

#     - name: Run Takeaways Formatting options test
#       env:
#         CLIENT_ID: ${{ secrets.CLIENT_ID }}
#         CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
#         PASSWORD: ${{ secrets.PASSWORD }}
#         USERNAME: ${{ secrets.USERNAME }}
#       continue-on-error: true
#       run: npm run takeawayformatting 


#     - name: Run Playwright content filter test 
#       env:
#         CLIENT_ID: ${{ secrets.CLIENT_ID }}
#         CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
#         PASSWORD: ${{ secrets.PASSWORD }}
#         USERNAME: ${{ secrets.USERNAME }}
#       continue-on-error: true
#       run: npm run content

#     - name: Run edit innerview
#       env:
#         CLIENT_ID: ${{ secrets.CLIENT_ID }}
#         CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
#         PASSWORD: ${{ secrets.PASSWORD }}
#         USERNAME: ${{ secrets.USERNAME }}
#       continue-on-error: true
#       run: npm run editinnerview

#     - name: Run playwright Delete link outercard test
#       env:
#         CLIENT_ID: ${{ secrets.CLIENT_ID }}
#         CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
#         PASSWORD: ${{ secrets.PASSWORD }}
#         USERNAME: ${{ secrets.USERNAME }} 
#       continue-on-error: true
#       run: npm run delete

#     - name: Run Delete link innerview test 
#       env:
#         CLIENT_ID: ${{ secrets.CLIENT_ID }}
#         CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
#         PASSWORD: ${{ secrets.PASSWORD }}
#         USERNAME: ${{ secrets.USERNAME }}
#       continue-on-error: true
#       run: npm run deleteinnerview
      

#     - name: Run edit popup Outercard
#       env:
#         CLIENT_ID: ${{ secrets.CLIENT_ID }}
#         CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
#         PASSWORD: ${{ secrets.PASSWORD }}
#         USERNAME: ${{ secrets.USERNAME }}
#       continue-on-error: true
#       run: npm run editoutercard

#     - name: Run home page UI test
#       env:
#         CLIENT_ID: ${{ secrets.CLIENT_ID }}
#         CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
#         PASSWORD: ${{ secrets.PASSWORD }}
#         USERNAME: ${{ secrets.USERNAME }}
#       continue-on-error: true
#       run: npm run homepage


#     - name: Run Link innerview test
#       env:
#         CLIENT_ID: ${{ secrets.CLIENT_ID }}
#         CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
#         PASSWORD: ${{ secrets.PASSWORD }}
#         USERNAME: ${{ secrets.USERNAME }}
#       continue-on-error: true
#       run: npm run linkinnerview


#     - name: Run Link outercard Tests
#       env:
#         CLIENT_ID: ${{ secrets.CLIENT_ID }}
#         CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
#         PASSWORD: ${{ secrets.PASSWORD }}
#         USERNAME: ${{ secrets.USERNAME }}
#       continue-on-error: true
#       run: npm run linkoutercard


#     - name: Run PayItforward outercard tests
#       env:
#         CLIENT_ID: ${{ secrets.CLIENT_ID }}
#         CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
#         PASSWORD: ${{ secrets.PASSWORD }}
#         USERNAME: ${{ secrets.USERNAME }}
#       continue-on-error: true
#       run: npm run payourtercard


#     - name: Run pay it forward Innerview tests
#       env:
#         CLIENT_ID: ${{ secrets.CLIENT_ID }}
#         CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
#         PASSWORD: ${{ secrets.PASSWORD }}
#         USERNAME: ${{ secrets.USERNAME }} 
#       continue-on-error: true
#       run: npm run payinnerview


#     - name: recommend link
      
#       env:
#         CLIENT_ID: ${{ secrets.CLIENT_ID }}
#         CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
#         PASSWORD: ${{ secrets.PASSWORD }}
#         USERNAME: ${{ secrets.USERNAME }}
#       continue-on-error: true
#       run: npm run editinnerview
#       #continue-on-error: true
#       #run: node tests/access.js


#     - name: Run Recommend link innerview test
#       env:
#         CLIENT_ID: ${{ secrets.CLIENT_ID }}
#         CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
#         PASSWORD: ${{ secrets.PASSWORD }}
#         USERNAME: ${{ secrets.USERNAME }}
#       continue-on-error: true
#       run: npm run recommendinnerview


     

#     - name: Run Takeaways and remove progress test
#       env:
#         CLIENT_ID: ${{ secrets.CLIENT_ID }}
#         CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
#         PASSWORD: ${{ secrets.PASSWORD }}
#         USERNAME: ${{ secrets.USERNAME }}
#       continue-on-error: true
#       run: npm run takeawayremoveprogress
    
#     - uses: actions/upload-artifact@v3
#       if: always()
#       with:
#         name: playwright-report
#         path: playwright-report/
#         retention-days: 30
         
#     #"recommendhomepage": "tests/RecommendLinkHomePage.spec.js",
#    # "recommendinnerview": "tests/RecommendLinkInnerView.spec.js",
#    # "takeawayformatting": "tests/TakawayFormattingOption.spec.js",
#    # "takeawayremoveprogress": "tests/TakawayFormattingOption.spec.js"

 